# Permalinks
permalink:           pretty

# Setup
title:               Obaid ur Rehman
tagline:             Adventures in JavaScript Land
url:                 http://obaidurrehman.github.io/
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Obaid ur Rehman
  url:               https://twitter.com/obaidurrehmann
  email:             obaid@live.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ObaidurRehman

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
